#!/usr/bin/env python3
"""Inject research/<id>.availability.json into data.js without rebuilding images.

build.py is the canonical path, but it needs research/raw/ (not committed) and will
drop every image if that folder is absent. This script edits data.js in place instead:
it reads the window.VENUES array already there and refreshes only the "verified" key.

Usage: python3 apply_availability.py
"""
import json, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
RESEARCH = os.path.join(ROOT, "research")
DATA = os.path.join(ROOT, "data.js")

WEEKENDS = [
    "2026-08-28", "2026-09-04", "2026-09-11", "2026-09-18", "2026-09-25",
    "2026-10-02", "2026-10-09", "2026-10-16", "2026-10-23", "2026-10-30",
]
STATUSES = {
    "definitely_available", "probably_available", "unknown",
    "probably_not_available", "definitely_not_available",
}


def load_data_js():
    src = open(DATA).read()
    start = src.index("window.VENUES = ") + len("window.VENUES = ")
    end = src.rindex(";")
    return json.loads(src[start:end])


def verified_for(vid):
    path = os.path.join(RESEARCH, f"{vid}.availability.json")
    if not os.path.exists(path):
        return None, ["no availability file"]
    av = json.load(open(path))
    problems = []
    by_weekend = {}
    for w in av.get("weekends") or []:
        wk = w.get("weekend")
        if wk not in WEEKENDS:
            problems.append(f"unexpected weekend {wk!r}")
            continue
        status = w.get("status", "unknown")
        if status not in STATUSES:
            problems.append(f"{wk}: bad status {status!r}")
            status = "unknown"
        if status != "unknown" and not w.get("source_url"):
            problems.append(f"{wk}: {status} with no source_url")
        by_weekend[wk] = {
            "weekend": wk,
            "status": status,
            "evidence": w.get("evidence", ""),
            "quote": w.get("evidence_quote") or "",
            "sourceUrl": w.get("source_url", ""),
            "sourceLabel": w.get("source_label", ""),
        }
    for wk in WEEKENDS:
        if wk not in by_weekend:
            problems.append(f"{wk}: missing")
            by_weekend[wk] = {
                "weekend": wk, "status": "unknown", "evidence": "",
                "quote": "", "sourceUrl": "", "sourceLabel": "",
            }
    return {
        "checkedOn": av.get("checked_on", ""),
        "method": av.get("method", ""),
        "bookingPolicy": av.get("booking_policy", ""),
        "weekends": [by_weekend[wk] for wk in WEEKENDS],
    }, problems


def main():
    venues = load_data_js()
    missing = []
    for v in venues:
        verified, problems = verified_for(v["id"])
        if verified is None:
            missing.append(v["id"])
            v.pop("verified", None)
            continue
        v["verified"] = verified
        counts = {}
        for w in verified["weekends"]:
            counts[w["status"]] = counts.get(w["status"], 0) + 1
        summary = " ".join(f"{k.split('_')[0][:4]}={n}" for k, n in sorted(counts.items()))
        print(f"{v['id']:26s} {summary}" + (f"   ! {'; '.join(problems)}" if problems else ""))
    with open(DATA, "w") as f:
        f.write("// Generated by build.py — do not edit by hand.\n")
        f.write("window.VENUES = ")
        json.dump(venues, f, ensure_ascii=False, indent=1)
        f.write(";\n")
    print(f"\n{len(venues) - len(missing)}/{len(venues)} venues have verified availability.")
    if missing:
        print("No availability file: " + ", ".join(missing))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
