// Generated by build.py — do not edit by hand.
window.VENUES = [
 {
  "id": "st-dorothys-rest",
  "tier": "A",
  "name": "St. Dorothy's Rest",
  "area": "Camp Meeker (nr. Occidental), Sonoma",
  "drive": "~1 hr 45 min",
  "sleeps": "112 beds total; 8-65 per building",
  "meeting": "Main hall 40' x 25' w/ stone fireplace; several smaller rooms + redwood chapel",
  "buyout": "Yes, whole site for groups of 68+",
  "why": "1901 redwood camp: shingled buildings, fireplaces, sleeping porches, dining porches, chapel in the trees. Closest thing to a Lighthaven-style campus you can actually book.",
  "watch": "Mixed room types (single/double/dorm); dorm bedding costs extra",
  "phone": "(707) 874-3319",
  "email": "retreats@stdorothysrest.org",
  "website": "https://www.saintdorothysrest.org/",
  "booking": "https://www.saintdorothysrest.org/retreats",
  "note": "Research note: the retreats page lists per-building bed counts (Main House, Farmer, Lydia, Upper/Lower Miriam) and 2026 rates; 12-person minimum for meals; dorm bedding extra. Office hours Tue-Fri 10-5.",
  "tierLabel": "Tier A",
  "address": "168 St Dorothy Ave, Camp Meeker, CA 95419",
  "lat": 38.4289925,
  "lng": -122.9640174,
  "geo_confidence": "high",
  "thumb": "images/st-dorothys-rest/thumb.jpg",
  "images": [
   {
    "file": "images/st-dorothys-rest/01.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Redwood chapel with bell tower among the redwoods",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/"
   },
   {
    "file": "images/st-dorothys-rest/02.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Main House, the 1901 shingled lodge",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/retreats"
   },
   {
    "file": "images/st-dorothys-rest/03.jpg",
    "w": 1600,
    "h": 2125,
    "caption": "Guest building and deck in the redwoods at sunset",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/retreats"
   },
   {
    "file": "images/st-dorothys-rest/04.jpg",
    "w": 1600,
    "h": 1225,
    "caption": "Covered porch looking out over the Russian River hills",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/retreats"
   },
   {
    "file": "images/st-dorothys-rest/05.jpg",
    "w": 1024,
    "h": 592,
    "caption": "Chapel in afternoon light through the redwoods",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/about-us"
   },
   {
    "file": "images/st-dorothys-rest/06.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Ridge view from the property at dusk",
    "credit": "St. Dorothy's Rest (official site)",
    "source": "https://www.saintdorothysrest.org/"
   }
  ]
 },
 {
  "id": "green-mountain-retreat",
  "tier": "A",
  "name": "Green Mountain Retreat",
  "subtitle": "former Presentation Center",
  "area": "Los Gatos, Santa Cruz Mtns",
  "drive": "~1 hr 15 min (25 min from SJC)",
  "sleeps": "102 beds (cottages + dorm building)",
  "meeting": "Multiple meeting rooms; historically hosted groups of 5-200",
  "buyout": "Yes for a group your size",
  "why": "66 acres in the redwoods with a redwood amphitheater, cottages, indoor and outdoor gathering areas. Under new ownership/branding since the Presentation Center era.",
  "watch": "Newer operator, so ask what has actually been renovated",
  "phone": "(669) 269-8811",
  "email": "info@greenmountainretreat.com",
  "website": "https://www.greenmountainretreat.com/",
  "booking": "https://www.greenmountainretreat.com/contact",
  "tierLabel": "Tier A",
  "address": "19480 Bear Creek Rd, Los Gatos, CA 95033",
  "lat": 37.1731628,
  "lng": -122.008872,
  "geo_confidence": "high",
  "thumb": "images/green-mountain-retreat/thumb.jpg",
  "images": [
   {
    "file": "images/green-mountain-retreat/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Labyrinth on the front lawn with the white stucco main building behind",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/retreats"
   },
   {
    "file": "images/green-mountain-retreat/02.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Conference/meeting building in the meadow, redwoods behind",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/"
   },
   {
    "file": "images/green-mountain-retreat/03.jpg",
    "w": 1600,
    "h": 747,
    "caption": "Redwood amphitheater (panorama)",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/"
   },
   {
    "file": "images/green-mountain-retreat/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Lounge with carved stone fireplace in the main building",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/"
   },
   {
    "file": "images/green-mountain-retreat/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Dining hall (capacity 120, doubles as meeting space)",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/retreats"
   },
   {
    "file": "images/green-mountain-retreat/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Casa cottage with covered porch",
    "credit": "Green Mountain Retreat (official site)",
    "source": "https://www.greenmountainretreat.com/lodging"
   }
  ]
 },
 {
  "id": "westerbeke-ranch",
  "tier": "A",
  "name": "Westerbeke Ranch",
  "area": "Sonoma",
  "drive": "~1 hr 10 min",
  "sleeps": "40-52 (exclusive use billed at 40 minimum)",
  "meeting": "Casa Nueva ~80 classroom style; several breakouts",
  "buyout": "Yes, explicit exclusive-use contract",
  "why": "Five-generation family homestead: adobe, Mexican tile, gardens, pool, hot tub, chapel. Warm and lived-in rather than corporate. Very close analog to SSS Ranch.",
  "watch": "Overnight cap is right at or slightly under 60, so a few people may need to commute or double up",
  "phone": "(707) 996-7546",
  "email": "Info@WestRanch.com",
  "website": "https://www.thewesterbekeranch.com/",
  "booking": "https://www.thewesterbekeranch.com/yourstay/rates-resources/",
  "note": "Research note: meeting rooms on site are Casa Nueva and the Round House; cabins are color-named. The venue's photo library is low resolution, hence the softer images here.",
  "tierLabel": "Tier A",
  "address": "2300 Grove Street, Sonoma, CA 95476",
  "lat": 38.2931091,
  "lng": -122.5196168,
  "geo_confidence": "high",
  "thumb": "images/westerbeke-ranch/thumb.jpg",
  "images": [
   {
    "file": "images/westerbeke-ranch/01.jpg",
    "w": 800,
    "h": 460,
    "caption": "Adobe main house patio with Mexican tile roof and equipale chairs",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/explore/gallery/"
   },
   {
    "file": "images/westerbeke-ranch/02.jpg",
    "w": 800,
    "h": 507,
    "caption": "Pool and main house from the lawn under the oaks",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/explore/gallery/"
   },
   {
    "file": "images/westerbeke-ranch/03.jpg",
    "w": 800,
    "h": 531,
    "caption": "Dining room with stone fireplace and papel picado",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/explore/gallery/"
   },
   {
    "file": "images/westerbeke-ranch/04.jpg",
    "w": 800,
    "h": 413,
    "caption": "Casa Nueva meeting room set for a meditation retreat",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/explore/gallery/"
   },
   {
    "file": "images/westerbeke-ranch/05.jpg",
    "w": 800,
    "h": 533,
    "caption": "Yellow guest cabin with porch",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/yourstay/cabins/"
   },
   {
    "file": "images/westerbeke-ranch/06.jpg",
    "w": 800,
    "h": 515,
    "caption": "The Round House meeting room",
    "credit": "Westerbeke Ranch (official site)",
    "source": "https://www.thewesterbekeranch.com/explore/gallery/"
   }
  ]
 },
 {
  "id": "waterfall-lodge",
  "tier": "A",
  "name": "Waterfall Lodge & Retreat",
  "area": "Ben Lomond, Santa Cruz Mtns",
  "drive": "~1 hr 30 min (30 min from San Jose)",
  "sleeps": "86 in 32 cabins and cottages",
  "meeting": "150 day guests; big reclaimed-barnwood lodge",
  "buyout": "Yes, whole-property rental",
  "why": "80 private acres of redwoods with an actual waterfall, a hand-built lodge from 19th-c. reclaimed timber, meadow, bring-your-own-vendor policy. Design-forward and quirky.",
  "watch": "Mostly a wedding venue, so push them on conference AV and breakout rooms",
  "phone": "(831) 212-3895",
  "email": "hello@waterfallsantacruz.com",
  "website": "https://www.waterfallsantacruz.com/",
  "booking": "https://www.waterfallsantacruz.com/corporate",
  "tierLabel": "Tier A",
  "address": "325 Hidden Falls Trail, Ben Lomond, CA 95005",
  "lat": 37.0928319,
  "lng": -122.1160957,
  "geo_confidence": "high",
  "thumb": "images/waterfall-lodge/thumb.jpg",
  "images": [
   {
    "file": "images/waterfall-lodge/01.jpg",
    "w": 1600,
    "h": 1069,
    "caption": "The reclaimed-barnwood lodge and paver courtyard",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/virtual-tour/lodge"
   },
   {
    "file": "images/waterfall-lodge/02.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "A-frame cabins on stilts in the redwoods",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/"
   },
   {
    "file": "images/waterfall-lodge/03.jpg",
    "w": 1600,
    "h": 1069,
    "caption": "Lodge interior: open timber-frame hall",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/virtual-tour/lodge"
   },
   {
    "file": "images/waterfall-lodge/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Redwood grove ceremony/gathering site",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/"
   },
   {
    "file": "images/waterfall-lodge/05.jpg",
    "w": 1600,
    "h": 1069,
    "caption": "Lodge side entrance and stone patio",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/virtual-tour/lodge"
   },
   {
    "file": "images/waterfall-lodge/06.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Outdoor gathering clearing in the redwoods (aerial)",
    "credit": "Waterfall Lodge & Retreat (official site)",
    "source": "https://www.waterfallsantacruz.com/virtual-tour/ceremonylocations"
   }
  ]
 },
 {
  "id": "lodge-at-marconi",
  "tier": "A",
  "name": "Lodge at Marconi",
  "area": "Marshall, Tomales Bay",
  "drive": "~1 hr 30 min",
  "sleeps": "45 rooms, sleeps up to 100",
  "meeting": "8 event spaces: Tower Hill 250, Buck Hall 100, Cypress/Pine 45 each, amphitheatre 40",
  "buyout": "Ask; property is small enough that 60 nearly fills it",
  "why": "62-acre state historic park on a hillside over Tomales Bay. Site of Marconi's 1913 wireless station, later Synanon. Mid-century Bay Region architecture, recently and expensively redone.",
  "watch": "Priciest of the Marin options; oyster-country food scene is a plus",
  "phone": "(415) 663-9020",
  "email": "",
  "website": "https://lodgeatmarconi.com/",
  "booking": "https://lodgeatmarconi.com/gather/",
  "tierLabel": "Tier A",
  "address": "18500 State Hwy 1, Marshall, CA 94940",
  "lat": 38.144256,
  "lng": -122.8780054,
  "geo_confidence": "high",
  "thumb": "images/lodge-at-marconi/thumb.jpg",
  "images": [
   {
    "file": "images/lodge-at-marconi/01.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Guest lodges and fire circle under the pines",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/"
   },
   {
    "file": "images/lodge-at-marconi/02.jpg",
    "w": 1600,
    "h": 1198,
    "caption": "Aerial of the lodge buildings on the hillside above Tomales Bay",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/"
   },
   {
    "file": "images/lodge-at-marconi/03.jpg",
    "w": 1600,
    "h": 1199,
    "caption": "Aerial of the 62-acre state historic park and Tomales Bay",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/the-park/"
   },
   {
    "file": "images/lodge-at-marconi/04.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Mable's restaurant dining room",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/gather/"
   },
   {
    "file": "images/lodge-at-marconi/05.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Buck Hall event space",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/gather/"
   },
   {
    "file": "images/lodge-at-marconi/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Outdoor amphitheater benches in the woods",
    "credit": "Lodge at Marconi (official site)",
    "source": "https://lodgeatmarconi.com/gather/"
   }
  ]
 },
 {
  "id": "the-land",
  "tier": "A",
  "name": "The Land",
  "area": "Philo, Anderson Valley",
  "drive": "~2 hr 45 min",
  "sleeps": "90 beds: 18 cabins, 12 glamping tents, 8 houses",
  "meeting": "Lodge plus multiple gathering spaces; scales to 250 with tents",
  "buyout": "Yes; they say they specialize in groups of 20-60",
  "why": "162 acres of redwoods and a 5-acre organic garden, farm-to-table meals, river swimming. Explicitly built around groups the exact size you are running.",
  "watch": "Long drive; carpool logistics matter",
  "phone": "(707) 485-3117",
  "email": "info@the-land.us",
  "website": "https://the-land.us/",
  "booking": "https://the-land.us/contact",
  "note": "Research note: the site now also brands the property as 'The Eros Monastery' with practice-infused stays; it is 18+ only and alcohol- and cannabis-free. Verizon has no signal on site (AT&T and T-Mobile do).",
  "tierLabel": "Tier A",
  "address": "18501 Van Zandt Resort Rd, Philo, CA 95466",
  "lat": 39.05195,
  "lng": -123.44851,
  "geo_confidence": "high",
  "thumb": "images/the-land/thumb.jpg",
  "images": [
   {
    "file": "images/the-land/01.jpg",
    "w": 1500,
    "h": 842,
    "caption": "Two-story redwood lodge building with green metal roof, set among oaks and redwoods",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/corporate-retreats"
   },
   {
    "file": "images/the-land/02.jpg",
    "w": 1600,
    "h": 863,
    "caption": "Aerial view of the Navarro River winding through redwood forest on the property",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/"
   },
   {
    "file": "images/the-land/03.jpg",
    "w": 1200,
    "h": 1200,
    "caption": "Dining lodge interior with long tables and stone fireplace",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/gallery"
   },
   {
    "file": "images/the-land/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Timber-frame practice / meeting hall interior with cushions",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/gallery"
   },
   {
    "file": "images/the-land/05.jpg",
    "w": 1200,
    "h": 1200,
    "caption": "Glamping tents under the redwoods",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/explore-the-land"
   },
   {
    "file": "images/the-land/06.jpg",
    "w": 1200,
    "h": 1198,
    "caption": "Lodge at dusk with string lights over the outdoor seating area",
    "credit": "The Land (official site)",
    "source": "https://the-land.us/gallery"
   }
  ]
 },
 {
  "id": "camp-navarro",
  "tier": "A",
  "name": "Camp Navarro",
  "area": "Navarro, Mendocino County",
  "drive": "~2 hr 30 min",
  "sleeps": "240-260 beds (32 cabins, 54 glamping, camping)",
  "meeting": "Great Hall 4,600 sq ft, seats 400 for dinner; kitchen for 500+",
  "buyout": "Yes, full site",
  "why": "Historic 1930s Masonite company camp in 200 acres of redwoods. This is where real conferences and festivals go. Enormous character, real infrastructure.",
  "watch": "Way bigger than 60, so you pay for scale you will not use; they explicitly do not take booking calls",
  "phone": "No phone inquiries (policy)",
  "email": "inquiry@campnavarroca.com",
  "website": "https://www.campnavarro.com/",
  "booking": "https://www.campnavarro.com/inquiryrequest",
  "note": "Research note: the physical address is 901 Masonite Industrial Rd, Navarro. Booking inquiries go to inquiry@campnavarroca.com; site tours are by approved request only.",
  "tierLabel": "Tier A",
  "address": "901 Masonite Industrial Rd, Navarro, CA 95463",
  "lat": 39.16911,
  "lng": -123.56673,
  "geo_confidence": "high",
  "thumb": "images/camp-navarro/thumb.jpg",
  "images": [
   {
    "file": "images/camp-navarro/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "The historic two-story lodge (Great Hall) seen across the main lawn, redwoods behind",
    "credit": "Camp Navarro (official site)",
    "source": "https://www.campnavarro.com/photo-gallery"
   },
   {
    "file": "images/camp-navarro/02.jpg",
    "w": 1600,
    "h": 1199,
    "caption": "Aerial view of the plaza, lodge, tent village and the Navarro River",
    "credit": "Camp Navarro (official site)",
    "source": "https://www.campnavarro.com/photo-gallery"
   },
   {
    "file": "images/camp-navarro/03.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Cluster of 1930s-era cabins among the redwoods",
    "credit": "Camp Navarro (official site); photo Colin McCarthy",
    "source": "https://www.campnavarro.com/photo-gallery"
   },
   {
    "file": "images/camp-navarro/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Group meeting circle on benches in the redwood grove",
    "credit": "Camp Navarro (official site)",
    "source": "https://www.campnavarro.com/photo-gallery"
   },
   {
    "file": "images/camp-navarro/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Cabin interior (the 'Commish' cabin) with wood paneling and French doors",
    "credit": "Camp Navarro (official site)",
    "source": "https://www.campnavarro.com/photo-gallery"
   },
   {
    "file": "images/camp-navarro/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Glamping tipis set among the redwoods",
    "credit": "Camp Navarro (official site)",
    "source": "https://www.campnavarro.com/photo-gallery"
   }
  ]
 },
 {
  "id": "enchanted-hills",
  "tier": "B",
  "name": "Enchanted Hills",
  "area": "Napa (Mount Veeder)",
  "drive": "~1 hr 30 min",
  "sleeps": "Groups of 30-150",
  "meeting": "Dining hall, breakout rooms, outdoor amphitheater",
  "buyout": "Yes, off-season group rentals",
  "why": "311 acres of redwoods, creeks, ponds, a small lake, pool and amphitheater. Run by LightHouse for the Blind, so rental money funds the camp. Mid-October is their rental season.",
  "watch": "Rebuilt post-2017 fire; confirm which buildings are back online",
  "phone": "(707) 261-1101 / (415) 694-7310",
  "email": "events@lighthouse-sf.org",
  "website": "https://enchantedhillsnapa.org/",
  "booking": "https://enchantedhillsnapa.org/",
  "note": "Research note: now branded 'Enchanted Hills Napa'. Post-fire rebuild includes the Forest Commons dining/meeting hall, Hillside Village casitas, and Lakeside and Forest cabins plus tents and yurts.",
  "tierLabel": "Tier B",
  "address": "3410 Mt Veeder Rd, Napa, CA 94558",
  "lat": 38.38088,
  "lng": -122.43151,
  "geo_confidence": "high",
  "thumb": "images/enchanted-hills/thumb.jpg",
  "images": [
   {
    "file": "images/enchanted-hills/01.jpg",
    "w": 1600,
    "h": 790,
    "caption": "Forest Commons, the rebuilt modern dining and gathering hall, among redwoods and pines",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/experiences/meetings/"
   },
   {
    "file": "images/enchanted-hills/02.jpg",
    "w": 1206,
    "h": 866,
    "caption": "The camp lake with a paddle boat, surrounded by forest",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/explore/image-gallery/"
   },
   {
    "file": "images/enchanted-hills/03.jpg",
    "w": 1206,
    "h": 1037,
    "caption": "Forest Commons interior set for a dinner, with glass garage-door walls opening to the trees",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/experiences/weddings/"
   },
   {
    "file": "images/enchanted-hills/04.jpg",
    "w": 1600,
    "h": 790,
    "caption": "Large meeting room with conference tables and floor-to-ceiling windows",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/experiences/meetings/"
   },
   {
    "file": "images/enchanted-hills/05.jpg",
    "w": 1600,
    "h": 790,
    "caption": "New cabins (Hillside Village) set on the wooded slope",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/experiences/weddings/"
   },
   {
    "file": "images/enchanted-hills/06.jpg",
    "w": 1206,
    "h": 1277,
    "caption": "Swimming pool with guests",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/experiences/wellness/"
   },
   {
    "file": "images/enchanted-hills/07.jpg",
    "w": 1205,
    "h": 701,
    "caption": "Hillside Village cabins; note the fire-scarred trees behind, regrowing after the 2017 fire",
    "credit": "Enchanted Hills Napa / LightHouse for the Blind (official site)",
    "source": "https://enchantedhillsnapa.org/enchanted-hills-napa/accommodations/"
   }
  ]
 },
 {
  "id": "mount-madonna",
  "tier": "B",
  "name": "Mount Madonna Center",
  "area": "Watsonville (ridge above Monterey Bay)",
  "drive": "~1 hr 30 min",
  "sleeps": "Conference Center 33 rooms / 74 beds; plus yurts, cabins, glamping",
  "meeting": "Conference Center 250 theater style; Seminar House 40",
  "buyout": "Yes for the Conference Center building",
  "why": "Ridge-top campus with views to Monterey Bay, 380 acres, very well-run retreat operation, vegetarian kitchen. Unusually organized for this price band.",
  "watch": "Ashram-adjacent aesthetic; some cabins have no plumbing",
  "phone": "(408) 847-0406",
  "email": "hostyourgroup@mountmadonna.org",
  "website": "https://mountmadonna.org/",
  "booking": "https://mountmadonna.org/host-your-group/",
  "tierLabel": "Tier B",
  "address": "445 Summit Rd, Watsonville, CA 95076",
  "lat": 37.02558,
  "lng": -121.74461,
  "geo_confidence": "high",
  "thumb": "images/mount-madonna/thumb.jpg",
  "images": [
   {
    "file": "images/mount-madonna/01.jpg",
    "w": 1200,
    "h": 800,
    "caption": "Conference Center entrance courtyard and covered pavilion",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/host-your-group/"
   },
   {
    "file": "images/mount-madonna/02.jpg",
    "w": 1600,
    "h": 896,
    "caption": "Aerial view of the ridge-top campus with forested hills rolling toward Monterey Bay",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/"
   },
   {
    "file": "images/mount-madonna/03.jpg",
    "w": 1200,
    "h": 800,
    "caption": "Large meeting room in the Conference Center set with floor cushions and chairs",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/host-your-group/"
   },
   {
    "file": "images/mount-madonna/04.jpg",
    "w": 1200,
    "h": 800,
    "caption": "Conference Center patio with lounge chairs and the view over the forested ridge",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/host-your-group/"
   },
   {
    "file": "images/mount-madonna/05.jpg",
    "w": 1200,
    "h": 800,
    "caption": "Seminar House on its hillside among oaks and redwoods",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/host-your-group/"
   },
   {
    "file": "images/mount-madonna/06.jpg",
    "w": 1600,
    "h": 655,
    "caption": "Pond and meadow on the campus with Monterey Bay in the distance",
    "credit": "Mount Madonna Center (official site)",
    "source": "https://mountmadonna.org/about/our-campus/"
   }
  ]
 },
 {
  "id": "bishops-ranch",
  "tier": "B",
  "name": "The Bishop's Ranch",
  "area": "Healdsburg",
  "drive": "~1 hr 30 min",
  "sleeps": "Up to 80 adults",
  "meeting": "Conference hall up to 125; smallest room 12",
  "buyout": "Yes, Exclusive Use groups get booking priority",
  "why": "Vineyard-and-oak hillside ranch above the Russian River, mix of a rambling Ranch House, a lodge and five cottages. Quiet, handsome, unpretentious.",
  "watch": "Hosts nonprofit groups only, so the organizing entity matters",
  "phone": "(707) 433-2440",
  "email": "info@bishopsranch.org",
  "website": "https://www.bishopsranch.org/",
  "booking": "https://www.bishopsranch.org/group-reservations",
  "tierLabel": "Tier B",
  "address": "5297 Westside Rd, Healdsburg, CA 95448",
  "lat": 38.54404,
  "lng": -122.87396,
  "geo_confidence": "high",
  "thumb": "images/bishops-ranch/thumb.jpg",
  "images": [
   {
    "file": "images/bishops-ranch/01.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "The ivy-covered stone Ranch House, the historic heart of the property",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations/facilities"
   },
   {
    "file": "images/bishops-ranch/02.jpg",
    "w": 1600,
    "h": 899,
    "caption": "Aerial view of the ranch, pool and oak-studded hills above the Russian River valley",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations"
   },
   {
    "file": "images/bishops-ranch/03.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Interior of the large conference hall with wood floor and arched timber ceiling",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations/facilities"
   },
   {
    "file": "images/bishops-ranch/04.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "The Chapel of St. George on the lawn",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations/facilities"
   },
   {
    "file": "images/bishops-ranch/05.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Two-story lodge building with balconies, set among trees",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations/facilities"
   },
   {
    "file": "images/bishops-ranch/06.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Cottage living room with fireplace and vaulted ceiling",
    "credit": "The Bishop's Ranch (official site)",
    "source": "https://www.bishopsranch.org/group-reservations/facilities"
   }
  ]
 },
 {
  "id": "costanoa",
  "tier": "B",
  "name": "Costanoa",
  "area": "Pescadero (San Mateo coast)",
  "drive": "~1 hr",
  "sleeps": "39 lodge rooms, 14 cabins, 85 tent bungalows",
  "meeting": "Indoor rooms with patios plus outdoor/tented options; 150 capacity",
  "buyout": "Ask about buyout; shoulder season helps",
  "why": "Coastal bluff camp an hour from SF, surrounded by four state parks. Glamping-plus-lodge mix means you can flex the budget per attendee.",
  "watch": "Weather in mid-October on that coast can be cold and foggy at night",
  "phone": "(650) 879-1100",
  "email": "",
  "website": "https://www.costanoa.com/",
  "booking": "https://www.costanoa.com/request-proposal/",
  "tierLabel": "Tier B",
  "address": "2001 Rossi Road (at Hwy 1), Pescadero, CA 94060",
  "lat": 37.1555806,
  "lng": -122.3472231,
  "geo_confidence": "high",
  "thumb": "images/costanoa/thumb.jpg",
  "images": [
   {
    "file": "images/costanoa/01.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Main lodge exterior and lawn at dusk",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/stay/lodge/"
   },
   {
    "file": "images/costanoa/02.jpg",
    "w": 1600,
    "h": 972,
    "caption": "Aerial view of the lodge and grounds with the Pacific beyond",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/event-spaces/"
   },
   {
    "file": "images/costanoa/03.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Mountain-view cabins",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/stay/cabins/"
   },
   {
    "file": "images/costanoa/04.jpg",
    "w": 1600,
    "h": 946,
    "caption": "Lodge courtyard lit up at night",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/meetings/"
   },
   {
    "file": "images/costanoa/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Tent bungalows (glamping) on the lawn",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/photos/"
   },
   {
    "file": "images/costanoa/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Covered outdoor meeting/dining patio",
    "credit": "Costanoa (official site)",
    "source": "https://www.costanoa.com/"
   }
  ]
 },
 {
  "id": "saratoga-springs",
  "tier": "B",
  "name": "Saratoga Springs Retreat Center",
  "area": "Upper Lake, Lake County",
  "drive": "~2 hr 30 min",
  "sleeps": "Lodging plus camping; full site ~300",
  "meeting": "Heart Lodge 2,400 sq ft; 30-ft yurt for 40",
  "buyout": "Yes, exclusive use for groups of 25+",
  "why": "Weird in a good way: a 19th-century round house mineral pool, stone labyrinth, fire circle, hot soaking pool, springs. Cheap for exclusive use.",
  "watch": "Rustic; 2-10 night minimums; farther out",
  "phone": "(707) 275-9503",
  "email": "",
  "website": "https://saratogasprings.com/",
  "booking": "https://saratogasprings.com/retreat_facility.html",
  "note": "Research note: the official site is a frozen 2020 page with tiny photos, so the gallery here is thin. The center is still operating (it hosted a festival in Oct 2025); site text says exclusive use for groups of 25+, 2-10 night stays, 260 acres.",
  "tierLabel": "Tier B",
  "address": "10243 Saratoga Springs Rd, Upper Lake, CA 95485",
  "lat": 39.1748543,
  "lng": -122.9808979,
  "geo_confidence": "high",
  "thumb": "images/saratoga-springs/thumb.jpg",
  "images": [
   {
    "file": "images/saratoga-springs/01.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Historic main lodge under the valley oaks",
    "credit": "Saratoga Springs Retreat Center (official site)",
    "source": "https://saratogasprings.com/vintage/"
   },
   {
    "file": "images/saratoga-springs/02.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Main lodge front with double veranda",
    "credit": "Elacy via Wikipedia, CC BY-SA 3.0",
    "source": "https://en.wikipedia.org/wiki/File:Saratoge_Springs,_main_lodge.JPG"
   },
   {
    "file": "images/saratoga-springs/03.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Historic guest cabins",
    "credit": "Elacy via Wikipedia, CC BY-SA 3.0",
    "source": "https://en.wikipedia.org/wiki/File:Saratoga_Springs_cabins.JPG"
   },
   {
    "file": "images/saratoga-springs/04.jpg",
    "w": 745,
    "h": 535,
    "caption": "Entry drive past the lodge and cabins",
    "credit": "Lake County Tourism (lakecounty.com)",
    "source": "https://lakecounty.com/accommodation/saratoga-springs-retreat-and-conference-center/"
   }
  ]
 },
 {
  "id": "westminster-woods",
  "tier": "B",
  "name": "Westminster Woods",
  "area": "Occidental, Sonoma",
  "drive": "~1 hr 30 min",
  "sleeps": "Groups of 20-200; dorm cabins, 3 guest lodges, private rooms",
  "meeting": "Multiple meeting rooms with wifi, dining hall",
  "buyout": "Yes for a group of 60",
  "why": "200 acres of coastal redwoods on Dutch Bill Creek, next door to Occidental. During the school year they only take Friday-Sunday bookings, which is exactly your dates.",
  "watch": "Church-camp bones; dorm-heavy lodging",
  "phone": "(707) 874-2426",
  "email": "info@westminsterwoods.org",
  "website": "https://www.westminsterwoods.org/",
  "booking": "https://www.westminsterwoods.org/group-inquiries",
  "tierLabel": "Tier B",
  "address": "6510 Bohemian Hwy, Occidental, CA 95465",
  "lat": 38.4389615,
  "lng": -122.9750034,
  "geo_confidence": "medium",
  "thumb": "images/westminster-woods/thumb.jpg",
  "images": [
   {
    "file": "images/westminster-woods/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "The Woods Inn guest lodge in the redwoods",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   },
   {
    "file": "images/westminster-woods/02.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Homestead lodge exterior",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   },
   {
    "file": "images/westminster-woods/03.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Dorm cabin",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   },
   {
    "file": "images/westminster-woods/04.jpg",
    "w": 1136,
    "h": 852,
    "caption": "Hillside campfire amphitheater",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   },
   {
    "file": "images/westminster-woods/05.jpg",
    "w": 1600,
    "h": 946,
    "caption": "Homestead meeting room with stone fireplace",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   },
   {
    "file": "images/westminster-woods/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Meadow and redwoods",
    "credit": "Westminster Woods (official site)",
    "source": "https://www.westminsterwoods.org/facilities"
   }
  ]
 },
 {
  "id": "monte-toyon",
  "tier": "B",
  "name": "Monte Toyon",
  "area": "Aptos, Santa Cruz County",
  "drive": "~1 hr 30 min",
  "sleeps": "146 overnight",
  "meeting": "Day use 150; Helgesson Hall (stage, wood floor, good acoustics)",
  "buyout": "Yes at your size",
  "why": "Redwood camp minutes from the beach, run by UCCR so pricing is transparent and group-friendly. Meeting spaces are free for overnight groups.",
  "watch": "Plain camp aesthetic; less 'wow' than Tier A",
  "phone": "(800) 678-5102",
  "email": "reservations@uccr.org",
  "website": "https://www.uccr.org/monte-toyon",
  "booking": "https://www.uccr.org/monte-toyon",
  "tierLabel": "Tier B",
  "address": "220 Cloister Lane, Aptos, CA 95003",
  "lat": 36.996114,
  "lng": -121.896946,
  "geo_confidence": "high",
  "thumb": "images/monte-toyon/thumb.jpg",
  "images": [
   {
    "file": "images/monte-toyon/01.jpg",
    "w": 1600,
    "h": 1040,
    "caption": "Cary Lodge among the redwoods",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   },
   {
    "file": "images/monte-toyon/02.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Dining hall exterior with bell tower",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   },
   {
    "file": "images/monte-toyon/03.jpg",
    "w": 1600,
    "h": 1191,
    "caption": "Hall interior with wood floor and stone fireplace",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   },
   {
    "file": "images/monte-toyon/04.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Outdoor amphitheater and fire circle",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   },
   {
    "file": "images/monte-toyon/05.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Dining hall interior",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   },
   {
    "file": "images/monte-toyon/06.jpg",
    "w": 1600,
    "h": 1492,
    "caption": "Footbridge over the creek",
    "credit": "UCCR / Monte Toyon (official site)",
    "source": "https://www.uccr.org/monte-toyon"
   }
  ]
 },
 {
  "id": "vallombrosa",
  "tier": "B",
  "name": "Vallombrosa Center",
  "area": "Menlo Park",
  "drive": "~40 min",
  "sleeps": "60 guest rooms, up to 100 overnight",
  "meeting": "11 meeting rooms",
  "buyout": "Effectively, at 60 people",
  "why": "Walled 8-acre garden estate in downtown Menlo Park. Zero travel friction for a Bay Area crowd, walkable to town and Caltrain, private rooms for everyone.",
  "watch": "Restricted to religious, educational or charitable groups; suburban rather than scenic",
  "phone": "(650) 325-5614",
  "email": "jaynie@vallombrosa.org",
  "website": "https://www.vallombrosa.org/",
  "booking": "https://www.vallombrosa.org/retreats-conferences-programs/",
  "tierLabel": "Tier B",
  "address": "250 Oak Grove Avenue, Menlo Park, CA 94025",
  "lat": 37.4602497,
  "lng": -122.1813261,
  "geo_confidence": "high",
  "thumb": "images/vallombrosa/thumb.jpg",
  "images": [
   {
    "file": "images/vallombrosa/01.jpg",
    "w": 1600,
    "h": 1062,
    "caption": "The 1920s mansion, Vallombrosa's main house",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/mlb_5791_hdr/"
   },
   {
    "file": "images/vallombrosa/02.jpg",
    "w": 1600,
    "h": 1063,
    "caption": "Great oak on the lawn",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/tour/"
   },
   {
    "file": "images/vallombrosa/03.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Guest-room wing and garden",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/val1-311/"
   },
   {
    "file": "images/vallombrosa/04.jpg",
    "w": 1600,
    "h": 1201,
    "caption": "East Parlor meeting room",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/meet-rooms/"
   },
   {
    "file": "images/vallombrosa/05.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Tree-lined entry drive",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/val1-317/"
   },
   {
    "file": "images/vallombrosa/06.jpg",
    "w": 1600,
    "h": 589,
    "caption": "Front gate on Oak Grove Avenue (wide banner crop)",
    "credit": "Vallombrosa Center (official site)",
    "source": "https://www.vallombrosa.org/"
   }
  ]
 },
 {
  "id": "ymca-point-bonita",
  "tier": "B",
  "name": "NatureBridge Golden Gate",
  "area": "Marin Headlands, Sausalito",
  "drive": "~25 min",
  "sleeps": "Dorm lodging on two campuses (Bluff at Point Bonita, Beach at Fort Cronkhite); up to 200 guests total",
  "meeting": "4 meeting rooms: Coast 20-49, Raven 30-62, Cypress 30-97, Sunset 50-130",
  "buyout": "Ask; with two campuses, 60 can likely have the Bluff campus to itself",
  "why": "A 5.2-acre former army post inside the Golden Gate National Recreation Area, ocean beaches and Golden Gate views out the window. Cheapest good option and absurdly close to the city.",
  "watch": "Bunk dorms and shared baths; institutional interiors. The YMCA no longer runs it: NatureBridge took over in Nov 2023, so the sheet's YMCA phone is stale",
  "phone": "",
  "email": "Via naturebridge.org inquiry form",
  "website": "https://naturebridge.org/retreat-space/golden-gate",
  "booking": "https://naturebridge.org/retreat-space/golden-gate",
  "subtitle": "former YMCA Point Bonita",
  "note": "Research note: the YMCA of SF closed this site; NatureBridge now markets it as the Golden Gate Conference & Retreat Center. Published 2026 rates are about $157-162 per person per night ($136-141 for nonprofits). Overnight availability is Fri-Sun during the school year, which fits Oct 16-18.",
  "tierLabel": "Tier B",
  "address": "981 Fort Barry, Sausalito, CA 94965",
  "lat": 37.823231,
  "lng": -122.529494,
  "geo_confidence": "high",
  "thumb": "images/ymca-point-bonita/thumb.jpg",
  "images": [
   {
    "file": "images/ymca-point-bonita/01.jpg",
    "w": 1400,
    "h": 800,
    "caption": "Aerial view of the Point Bonita campus on the Marin Headlands bluff, Golden Gate Bridge and San Francisco skyline beyond",
    "credit": "YMCA of San Francisco (archived official site, via Wayback Machine)",
    "source": "http://web.archive.org/web/20210920090616/https://www.ymcasf.org/locations/point-bonita-ymca/visiting-point-bonita"
   },
   {
    "file": "images/ymca-point-bonita/02.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Campus basketball court and green dormitory building among coastal scrub",
    "credit": "YMCA of San Francisco (archived official site, via Wayback Machine)",
    "source": "http://web.archive.org/web/20230120113022/https://www.ymcasf.org/locations/point-bonita-ymca"
   },
   {
    "file": "images/ymca-point-bonita/03.jpg",
    "w": 1600,
    "h": 701,
    "caption": "Panorama of the Point Bonita 'Bluff' campus buildings with a rainbow over Rodeo Beach",
    "credit": "NatureBridge (current operator, official site)",
    "source": "https://naturebridge.org/locations/golden-gate"
   },
   {
    "file": "images/ymca-point-bonita/04.jpg",
    "w": 1000,
    "h": 714,
    "caption": "Point Bonita dining hall with checkerboard floor and buffet line",
    "credit": "NatureBridge (current operator, official site)",
    "source": "https://naturebridge.org/locations/golden-gate"
   },
   {
    "file": "images/ymca-point-bonita/05.jpg",
    "w": 1200,
    "h": 800,
    "caption": "Rodeo Beach surf below the campus",
    "credit": "YMCA of San Francisco (archived official site, via Wayback Machine)",
    "source": "http://web.archive.org/web/20230120113022/https://www.ymcasf.org/locations/point-bonita-ymca"
   },
   {
    "file": "images/ymca-point-bonita/06.jpg",
    "w": 960,
    "h": 720,
    "caption": "Hikers on the headlands bluff trail above the Pacific",
    "credit": "YMCA of San Francisco (archived official site, via Wayback Machine)",
    "source": "http://web.archive.org/web/20230120113022/https://www.ymcasf.org/locations/point-bonita-ymca"
   }
  ]
 },
 {
  "id": "walker-creek-ranch",
  "tier": "B",
  "name": "Walker Creek Ranch",
  "area": "Petaluma / Marshall, West Marin",
  "drive": "~1 hr 15 min",
  "sleeps": "Conference center lodging (confirm counts)",
  "meeting": "Conference center plus multiple meeting rooms",
  "buyout": "Yes, they take private conference bookings",
  "why": "1,741 acres of West Marin ranchland run by Marin County, big open space, dark skies, low cost.",
  "watch": "Primarily an outdoor school; ask what else is on site that weekend",
  "phone": "(415) 491-6603",
  "email": "jparker@marinschools.org",
  "website": "https://www.walkercreekranch.org/",
  "booking": "https://www.walkercreekranch.org/",
  "note": "Research note: the conference-center contact on the site is (415) 491-6603 / jparker@marinschools.org (the sheet had the main office line). Lodging is four lodges with 2-5 bed rooms, 13 bunk cabins, two bunkhouses and camping.",
  "tierLabel": "Tier B",
  "address": "1700 Marshall Petaluma Rd, Petaluma, CA 94952",
  "lat": 38.17374,
  "lng": -122.81402,
  "geo_confidence": "high",
  "thumb": "images/walker-creek-ranch/thumb.jpg",
  "images": [
   {
    "file": "images/walker-creek-ranch/01.jpg",
    "w": 1529,
    "h": 1108,
    "caption": "Spring poppies on the hill trail above the main campus in the Walker Creek valley",
    "credit": "Walker Creek Ranch (official site)",
    "source": "https://www.walkercreekranch.org/floor-plans-maps"
   },
   {
    "file": "images/walker-creek-ranch/02.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "The 1,741-acre ranch property with Turtle Pond and the campus buildings in the valley",
    "credit": "Walker Creek Ranch (official site)",
    "source": "https://www.walkercreekranch.org/floor-plans-maps"
   },
   {
    "file": "images/walker-creek-ranch/03.jpg",
    "w": 1600,
    "h": 1153,
    "caption": "Willow Lodge meeting room / lounge",
    "credit": "Walker Creek Ranch (official site)",
    "source": "https://www.walkercreekranch.org/floor-plans-maps"
   },
   {
    "file": "images/walker-creek-ranch/04.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Lodge guest room with two beds",
    "credit": "Walker Creek Ranch (official site)",
    "source": "https://www.walkercreekranch.org/lodging"
   },
   {
    "file": "images/walker-creek-ranch/05.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Rock outcrop on Walker Peak overlooking the West Marin hills",
    "credit": "Walker Creek Ranch (official site)",
    "source": "https://www.walkercreekranch.org/plan-your-event-1"
   }
  ]
 },
 {
  "id": "harbin-hot-springs",
  "tier": "C",
  "name": "Harbin Hot Springs",
  "area": "Middletown, Lake County",
  "drive": "~2 hr 15 min",
  "sleeps": "Cabins, camping, lodging across 280 acres",
  "meeting": "Event spaces for gatherings and workshops",
  "buyout": "Group retreats hosted regularly",
  "why": "Eight thermal pools, 1,700+ acres of land, EcoFarm, deeply countercultural. Memorable in a way a hotel never is.",
  "watch": "Clothing-optional culture; you would need to brief attendees; not a polished conference plant",
  "phone": "(707) 987-2477",
  "email": "info@harbin.org",
  "website": "https://harbin.org/",
  "booking": "https://harbin.org/experience/",
  "note": "Research note: the post-2015-fire rebuild is still in progress. A new restaurant opened in August 2026 and a new multi-story hotel is being finished; current lodging is domes, hotel rooms, caravans and tent camping.",
  "tierLabel": "Tier C",
  "address": "18424 Harbin Springs Rd, Middletown, CA 95461",
  "lat": 38.78608,
  "lng": -122.65183,
  "geo_confidence": "high",
  "thumb": "images/harbin-hot-springs/thumb.jpg",
  "images": [
   {
    "file": "images/harbin-hot-springs/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "The rebuilt pool building with its stained-glass gable and the warm pool",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/"
   },
   {
    "file": "images/harbin-hot-springs/02.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Dome guest accommodations beside the pool area",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/reservations/accommodations-rates/"
   },
   {
    "file": "images/harbin-hot-springs/03.jpg",
    "w": 1080,
    "h": 810,
    "caption": "The new hotel building on the hillside above the stone labyrinth and gazebo",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/heart-consciousness/photos/"
   },
   {
    "file": "images/harbin-hot-springs/04.jpg",
    "w": 1440,
    "h": 810,
    "caption": "Front of the new restaurant building (opened August 2026)",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/heart-consciousness/photos/"
   },
   {
    "file": "images/harbin-hot-springs/05.jpg",
    "w": 1080,
    "h": 810,
    "caption": "Garden pavilion among flowering shrubs",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/heart-consciousness/photos/"
   },
   {
    "file": "images/harbin-hot-springs/06.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Hotel guest room with queen bed and sitting area",
    "credit": "Harbin Hot Springs (official site)",
    "source": "https://harbin.org/reservations/accommodations-rates/"
   }
  ]
 },
 {
  "id": "wilbur-hot-springs",
  "tier": "C",
  "name": "Wilbur Hot Springs",
  "area": "Williams, Colusa County",
  "drive": "~2 hr 30 min",
  "sleeps": "~40-50 across historic hotel, cabins, bunk rooms",
  "meeting": "Common areas; no dedicated large conference hall",
  "buyout": "Yes, they do full-site buyouts",
  "why": "Off-grid solar lodge from 1915 on an 1,800-acre private nature preserve. Total disconnection, natural mineral flumes. Singular.",
  "watch": "Probably tops out below 60 beds; very limited connectivity",
  "phone": "(530) 777-2306",
  "email": "frontdesk@wilburhotsprings.com",
  "website": "https://www.wilburhotsprings.com/",
  "booking": "https://www.wilburhotsprings.com/reservations/rooms-rates/",
  "tierLabel": "Tier C",
  "address": "3375 Wilbur Springs Rd, Williams, CA 95987",
  "lat": 39.03879,
  "lng": -122.42115,
  "geo_confidence": "high",
  "thumb": "images/wilbur-hot-springs/thumb.jpg",
  "images": [
   {
    "file": "images/wilbur-hot-springs/01.jpg",
    "w": 1000,
    "h": 750,
    "caption": "The open-air Fluminarium bathhouse and soaking pool above Sulphur Creek",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/reservations/rooms-rates/"
   },
   {
    "file": "images/wilbur-hot-springs/02.jpg",
    "w": 1536,
    "h": 942,
    "caption": "The resort in its canyon: historic hotel (left), cabins and outbuildings below the nature-preserve hills",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/photos/vistas/"
   },
   {
    "file": "images/wilbur-hot-springs/03.jpg",
    "w": 1600,
    "h": 923,
    "caption": "Guest cabins at sunset",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/"
   },
   {
    "file": "images/wilbur-hot-springs/04.jpg",
    "w": 1000,
    "h": 600,
    "caption": "Inside the Fluminarium: the three mineral-water flumes under a timber roof",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/photos/geothermal-springs/"
   },
   {
    "file": "images/wilbur-hot-springs/05.jpg",
    "w": 1200,
    "h": 791,
    "caption": "Solar Suite interior with canyon view",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/reservations/rooms-rates/"
   },
   {
    "file": "images/wilbur-hot-springs/06.jpg",
    "w": 1000,
    "h": 750,
    "caption": "Sulphur Creek and the bathhouse from the hillside",
    "credit": "Wilbur Hot Springs (official site)",
    "source": "https://www.wilburhotsprings.com/photos/vistas/"
   }
  ]
 },
 {
  "id": "asilomar",
  "tier": "C",
  "name": "Asilomar Conference Grounds",
  "area": "Pacific Grove, Monterey Peninsula",
  "drive": "~2 hr",
  "sleeps": "312 rooms in 30 buildings",
  "meeting": "Many meeting rooms; wood-beamed Crocker Dining Hall",
  "buyout": "No (state park concession), but you can block a wing",
  "why": "Julia Morgan's 1913 Arts-and-Crafts campus in the dunes on its own state beach. Architecturally the most Lighthaven-adjacent thing in Northern California.",
  "watch": "Shared with other groups; no TVs or phones in rooms; farthest south",
  "phone": "(888) 635-5310",
  "email": "",
  "website": "https://www.visitasilomar.com/",
  "booking": "https://www.visitasilomar.com/meetings-events/meetings-rfp",
  "tierLabel": "Tier C",
  "address": "800 Asilomar Ave, Pacific Grove, CA 93950",
  "lat": 36.618554,
  "lng": -121.938448,
  "geo_confidence": "high",
  "thumb": "images/asilomar/thumb.jpg",
  "images": [
   {
    "file": "images/asilomar/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Merrill Hall, Julia Morgan's stone-and-shingle auditorium (1928)",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/"
   },
   {
    "file": "images/asilomar/02.jpg",
    "w": 1600,
    "h": 1065,
    "caption": "Historic Arts-and-Crafts shingle building in the pines",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/gallery"
   },
   {
    "file": "images/asilomar/03.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Timber-beamed social hall lounge with stone fireplace",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/plan/asilomar-architecture"
   },
   {
    "file": "images/asilomar/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Merrill Hall interior from the balcony, trusses and theatre seating",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/"
   },
   {
    "file": "images/asilomar/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Crocker Dining Hall with its wood-beamed ceiling",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/"
   },
   {
    "file": "images/asilomar/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Asilomar State Beach shoreline at the edge of the grounds",
    "credit": "Asilomar Conference Grounds / Aramark (official site)",
    "source": "https://www.visitasilomar.com/gallery"
   }
  ]
 },
 {
  "id": "1440-multiversity",
  "tier": "C",
  "name": "1440 Multiversity",
  "area": "Scotts Valley, Santa Cruz Mtns",
  "drive": "~1 hr 15 min",
  "sleeps": "147 private guest rooms",
  "meeting": "40,000+ sq ft, 30+ indoor and outdoor venues, up to 300",
  "buyout": "No, but all-inclusive group packages",
  "why": "Purpose-built modern learning campus in the redwoods: great AV, infinity hot tub, all-inclusive pricing with three meals a day. The zero-hassle option.",
  "watch": "Most expensive on this list; polished-wellness aesthetic rather than idiosyncratic",
  "phone": "(888) 727-1440 (res) / (844) 544-1440",
  "email": "",
  "website": "https://www.1440.org/",
  "booking": "https://www.1440.org/groups",
  "tierLabel": "Tier C",
  "address": "800 Bethany Drive, Scotts Valley, CA 95066",
  "lat": 37.0751,
  "lng": -121.9947,
  "geo_confidence": "high",
  "thumb": "images/1440-multiversity/thumb.jpg",
  "images": [
   {
    "file": "images/1440-multiversity/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "The Lodge at dusk, with pond and footbridge",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/the-campus-gallery"
   },
   {
    "file": "images/1440-multiversity/02.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Campus entrance sign with Sanctuary building at dusk",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/the-campus-gallery"
   },
   {
    "file": "images/1440-multiversity/03.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Redwood Amphitheater, outdoor venue in the redwoods",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/outdoor-venues-gallery"
   },
   {
    "file": "images/1440-multiversity/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Redwood Auditorium set up for a conference",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/meeting-venues-gallery"
   },
   {
    "file": "images/1440-multiversity/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "The Sanctuary, timber-framed gathering hall interior",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/meeting-venues-gallery"
   },
   {
    "file": "images/1440-multiversity/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Kitchen Table dining hall",
    "credit": "1440 Multiversity (official site)",
    "source": "https://www.1440.org/dining-gallery"
   }
  ]
 },
 {
  "id": "mendocino-woodlands",
  "tier": "C",
  "name": "Mendocino Woodlands",
  "area": "Mendocino",
  "drive": "~3 hr 30 min",
  "sleeps": "Three separate camps, 30-200 each",
  "meeting": "Kitchen/dining/rec hall per camp, campfire circles",
  "buyout": "Yes, you rent an entire self-contained camp",
  "why": "720-acre National Historic Landmark, the only CCC-built 1930s group camp still operating as one. Looks exactly as it did in 1942.",
  "watch": "Very rustic and far; October nights are cold; you bring more of your own operation",
  "phone": "(707) 937-5755",
  "email": "director@mendocinowoodlands.org",
  "website": "https://www.mendocinowoodlands.org/",
  "booking": "https://www.mendocinowoodlands.org/bookings-events",
  "tierLabel": "Tier C",
  "address": "39350 Little Lake Road, Mendocino, CA 95460",
  "lat": 39.3182,
  "lng": -123.703,
  "geo_confidence": "high",
  "thumb": "images/mendocino-woodlands/thumb.jpg",
  "images": [
   {
    "file": "images/mendocino-woodlands/01.jpg",
    "w": 1600,
    "h": 1068,
    "caption": "CCC-built redwood cabin at Camp One",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/"
   },
   {
    "file": "images/mendocino-woodlands/02.jpg",
    "w": 1600,
    "h": 1068,
    "caption": "Camp One dance hall / recreation hall interior with stone fireplace",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/"
   },
   {
    "file": "images/mendocino-woodlands/03.jpg",
    "w": 1200,
    "h": 801,
    "caption": "Cabin and open-air shelter among the redwoods",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/"
   },
   {
    "file": "images/mendocino-woodlands/04.jpg",
    "w": 1200,
    "h": 801,
    "caption": "Cabin interior with stone fireplace and cots",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/"
   },
   {
    "file": "images/mendocino-woodlands/05.jpg",
    "w": 1528,
    "h": 1145,
    "caption": "Outdoor dining set up in a redwood grove",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/bookings-events"
   },
   {
    "file": "images/mendocino-woodlands/06.jpg",
    "w": 1600,
    "h": 1199,
    "caption": "Outdoor amphitheater / ceremony site",
    "credit": "Mendocino Woodlands Camp Association (official site)",
    "source": "https://www.mendocinowoodlands.org/bookings-events"
   }
  ]
 },
 {
  "id": "land-of-medicine-buddha",
  "tier": "C",
  "name": "Land of Medicine Buddha",
  "area": "Soquel, Santa Cruz County",
  "drive": "~1 hr 20 min",
  "sleeps": "Max 56 (19 guest rooms plus yurts and camping)",
  "meeting": "Meeting halls, dining hall open 24/7",
  "buyout": "Yes, exclusive group rentals",
  "why": "108 forested acres with a pilgrimage trail, quiet and cheap, 2-night minimum fits Fri-Sun perfectly.",
  "watch": "Caps at 56, so a few people commute or camp",
  "phone": "(831) 462-8383",
  "email": "",
  "website": "https://landofmedicinebuddha.org/",
  "booking": "https://landofmedicinebuddha.org/stay/group-rentals/",
  "note": "Research note: the sheet's stay.landofmedicinebuddha.org booking link was returning errors; the working group-rentals page is on the main domain.",
  "tierLabel": "Tier C",
  "address": "5800 Prescott Road, Soquel, CA 95073",
  "lat": 37.0109,
  "lng": -121.9344,
  "geo_confidence": "high",
  "thumb": "images/land-of-medicine-buddha/thumb.jpg",
  "images": [
   {
    "file": "images/land-of-medicine-buddha/01.jpg",
    "w": 1600,
    "h": 1044,
    "caption": "Wish-Fulfilling Temple exterior",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/sacred-sites/"
   },
   {
    "file": "images/land-of-medicine-buddha/02.jpg",
    "w": 1600,
    "h": 947,
    "caption": "Wish-Fulfilling Temple interior",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/visit/wish-fulfilling-temple/"
   },
   {
    "file": "images/land-of-medicine-buddha/03.jpg",
    "w": 1600,
    "h": 1080,
    "caption": "Entrance courtyard with prayer wheel pavilion, prayer flags and guest building",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/"
   },
   {
    "file": "images/land-of-medicine-buddha/04.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Wooden deck overlooking the meadow, used for outdoor sessions",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/stay/group-rentals/"
   },
   {
    "file": "images/land-of-medicine-buddha/05.jpg",
    "w": 1200,
    "h": 900,
    "caption": "Treetops guest-room building",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/stay/personal-getaway/"
   },
   {
    "file": "images/land-of-medicine-buddha/06.jpg",
    "w": 1284,
    "h": 982,
    "caption": "Gompa (meditation hall) interior",
    "credit": "Land of Medicine Buddha (official site)",
    "source": "https://landofmedicinebuddha.org/sacred-sites/"
   }
  ]
 },
 {
  "id": "presidio-lodging",
  "tier": "C",
  "name": "Presidio Lodging",
  "subtitle": "Inn + Lodge at the Presidio",
  "area": "San Francisco",
  "drive": "In the city",
  "sleeps": "68 rooms across two boutique hotels",
  "meeting": "Up to 200 attendees",
  "buyout": "Yes, full two-property buyout is an advertised product",
  "why": "A national park inside San Francisco: 19th-century brick barracks on the main post, Golden Gate views, everyone can fly in and Uber. The urban answer.",
  "watch": "Hotel rather than campus; no single big communal hall the way a camp has",
  "phone": "1-800-906-2871",
  "email": "",
  "website": "https://presidiolodging.com/",
  "booking": "https://presidiolodging.com/contact/",
  "tierLabel": "Tier C",
  "address": "Inn at the Presidio, 42 Moraga Avenue, San Francisco, CA 94129 (Lodge at the Presidio: 105 Montgomery Street, SF 94129)",
  "lat": 37.7971,
  "lng": -122.4578,
  "geo_confidence": "high",
  "thumb": "images/presidio-lodging/thumb.jpg",
  "images": [
   {
    "file": "images/presidio-lodging/01.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Inn at the Presidio (historic Pershing Hall) aerial view with Golden Gate Bridge behind",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/inn-at-the-presidio/"
   },
   {
    "file": "images/presidio-lodging/02.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Lodge at the Presidio, Montgomery Street barracks, aerial view toward the Golden Gate",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/lodge-at-the-presidio/"
   },
   {
    "file": "images/presidio-lodging/03.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Lodge at the Presidio front facade with Golden Gate Bridge view",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/lodge-at-the-presidio/"
   },
   {
    "file": "images/presidio-lodging/04.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Inn at the Presidio living room / lobby with fireplace",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/inn-at-the-presidio/"
   },
   {
    "file": "images/presidio-lodging/05.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Lodge at the Presidio lobby and breakfast room",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/lodge-at-the-presidio/"
   },
   {
    "file": "images/presidio-lodging/06.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Meeting room set up boardroom-style",
    "credit": "Presidio Lodging (official site)",
    "source": "https://presidiolodging.com/inn-at-the-presidio/meetings-events/"
   }
  ]
 },
 {
  "id": "hidden-villa",
  "tier": "C",
  "name": "Hidden Villa",
  "area": "Los Altos Hills",
  "drive": "~45 min",
  "sleeps": "Hostel sleeps 39 only",
  "meeting": "Dana Center, Duveneck House, Morgan Pavilion up to 60; site holds 200 day guests",
  "buyout": "Day buyout yes; lodging is the constraint",
  "why": "1,600-acre working farm and wilderness preserve in the hills above Silicon Valley, the oldest hostel on the Pacific Coast. Cheap day rates ($300-$850 per space).",
  "watch": "Only 39 beds, so this works as a day venue with off-site lodging",
  "phone": "(650) 949-8650",
  "email": "",
  "website": "https://www.hiddenvilla.org/",
  "booking": "https://www.hiddenvilla.org/meeting-retreats/",
  "note": "Research note: meeting spaces are the Dana Center, Duveneck House and Morgan Family Pavilion; the hostel sleeps 39.",
  "tierLabel": "Tier C",
  "address": "26870 Moody Road, Los Altos Hills, CA 94022",
  "lat": 37.354,
  "lng": -122.1563,
  "geo_confidence": "high",
  "thumb": "images/hidden-villa/thumb.jpg",
  "images": [
   {
    "file": "images/hidden-villa/01.jpg",
    "w": 720,
    "h": 480,
    "caption": "Duveneck House, the 1920s family home used for meetings and retreats",
    "credit": "Hidden Villa (official site)",
    "source": "https://www.hiddenvilla.org/meeting-retreats/"
   },
   {
    "file": "images/hidden-villa/02.jpg",
    "w": 1536,
    "h": 1024,
    "caption": "Farm pasture and barns in the Adobe Creek valley",
    "credit": "Hidden Villa (official site)",
    "source": "https://www.hiddenvilla.org/visit/plan-your-trip/"
   },
   {
    "file": "images/hidden-villa/03.jpg",
    "w": 1600,
    "h": 1908,
    "caption": "Hidden Villa and the Adobe Creek valley from the hills above Moody Road",
    "credit": "Dicklyon, Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hidden_Villa_Adobe_Creek_headwaters.jpg"
   },
   {
    "file": "images/hidden-villa/04.jpg",
    "w": 1600,
    "h": 1017,
    "caption": "Environmental education center building (straw-bale construction)",
    "credit": "Schmiebel, Wikimedia Commons, CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hidden_Villa_Education_Center_2010.jpg"
   },
   {
    "file": "images/hidden-villa/05.jpg",
    "w": 1120,
    "h": 1120,
    "caption": "Dana Center meeting hall interior with skylights and stone fireplace",
    "credit": "Hidden Villa (official site)",
    "source": "https://www.hiddenvilla.org/meeting-retreats/"
   },
   {
    "file": "images/hidden-villa/06.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Organic farm rows below the hills at sunset",
    "credit": "Hidden Villa (official site)",
    "source": "https://www.hiddenvilla.org/"
   }
  ]
 },
 {
  "id": "triple-s-ranch",
  "tier": "REF",
  "name": "Triple S Ranch",
  "subtitle": "your SSS example",
  "area": "Calistoga, Napa",
  "drive": "~1 hr 30 min",
  "sleeps": "34 single / 60 double occupancy",
  "meeting": "Multiple indoor and outdoor spaces, up to ~200 standing",
  "buyout": "Yes, exclusive use of the 14-acre estate",
  "why": "Your benchmark: restored antique barns, 1920s-50s cottages, a Victorian house, redwoods, pool, 20-person infinity hot tub.",
  "watch": "Listed for reference / price comparison",
  "phone": "(415) 760-3432",
  "email": "",
  "website": "https://www.triplesranchnapa.com/",
  "booking": "https://www.triplesranchnapa.com/overview-retreat",
  "tierLabel": "Reference",
  "address": "4600 Mountain Home Ranch Road, Calistoga, CA 94515",
  "lat": 38.57155,
  "lng": -122.63936,
  "geo_confidence": "high",
  "thumb": "images/triple-s-ranch/thumb.jpg",
  "images": [
   {
    "file": "images/triple-s-ranch/01.jpg",
    "w": 1280,
    "h": 853,
    "caption": "Restored event barn exterior at dusk, lit from inside",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/lodging"
   },
   {
    "file": "images/triple-s-ranch/02.jpg",
    "w": 853,
    "h": 853,
    "caption": "The Grand Victorian house at twilight",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/real-retreats-gallery"
   },
   {
    "file": "images/triple-s-ranch/03.jpg",
    "w": 1283,
    "h": 855,
    "caption": "Pool, pool house and outdoor fireplace at dusk",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/"
   },
   {
    "file": "images/triple-s-ranch/04.jpg",
    "w": 1500,
    "h": 1000,
    "caption": "Company retreat session inside the main barn",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/"
   },
   {
    "file": "images/triple-s-ranch/05.jpg",
    "w": 1024,
    "h": 683,
    "caption": "Wood-panelled lounge / living room interior",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/lodging"
   },
   {
    "file": "images/triple-s-ranch/06.jpg",
    "w": 1280,
    "h": 853,
    "caption": "Guest cabin with covered porch at dusk",
    "credit": "Triple S Ranch (official site)",
    "source": "https://www.triplesranchnapa.com/real-retreats-gallery"
   }
  ]
 },
 {
  "id": "mayacamas-ranch",
  "tier": "REF",
  "name": "Mayacamas Ranch",
  "area": "Calistoga, Napa",
  "drive": "~1 hr 45 min",
  "sleeps": "n/a",
  "meeting": "n/a",
  "buyout": "Not currently bookable",
  "why": "Was the iconic Bay Area exclusive-use retreat center until the 2017 Tubbs Fire. Now positioned as a 300-acre 'bioregional hub' seeking steward partners, not taking group bookings.",
  "watch": "Included so you do not waste time chasing it",
  "phone": "Not published",
  "email": "",
  "website": "https://mayacamasranch.com/",
  "booking": "https://mayacamasranch.com/the-invitation/",
  "tierLabel": "Reference",
  "address": "3975 Mountain Home Ranch Road, Calistoga, CA 94515",
  "lat": 38.56958,
  "lng": -122.65057,
  "geo_confidence": "high",
  "thumb": "images/mayacamas-ranch/thumb.jpg",
  "images": [
   {
    "file": "images/mayacamas-ranch/01.jpg",
    "w": 800,
    "h": 600,
    "caption": "Pool and sunset over the Mayacamas Mountains (pre-2017 fire)",
    "credit": "Mayacamas Ranch (official site, pre-fire, archived via Wayback Machine)",
    "source": "https://web.archive.org/web/20141013093910/http://mayacamasranch.com/gallery/gatherings/"
   },
   {
    "file": "images/mayacamas-ranch/02.jpg",
    "w": 700,
    "h": 600,
    "caption": "Main lodge deck set for an outdoor dinner (pre-2017 fire; building lost in the Tubbs Fire)",
    "credit": "Mayacamas Ranch (official site, pre-fire, archived via Wayback Machine)",
    "source": "https://web.archive.org/web/20150214033511/http://mayacamasranch.com/gallery/facilities/"
   },
   {
    "file": "images/mayacamas-ranch/03.jpg",
    "w": 960,
    "h": 500,
    "caption": "Lawn and umbrella looking out over the Mayacamas range (legacy photo on the current site)",
    "credit": "Mayacamas Ranch (official site)",
    "source": "https://mayacamasranch.com/"
   },
   {
    "file": "images/mayacamas-ranch/04.jpg",
    "w": 1600,
    "h": 1071,
    "caption": "Hidden Lake with a canoe, looking east (pre-2017 fire)",
    "credit": "Mayacamas Ranch (official site, pre-fire, archived via Wayback Machine)",
    "source": "https://web.archive.org/web/20170616221614/http://mayacamasranch.com/"
   },
   {
    "file": "images/mayacamas-ranch/05.jpg",
    "w": 960,
    "h": 500,
    "caption": "Rainbow over the grassland terrace, current post-fire landscape",
    "credit": "Mayacamas Ranch (official site)",
    "source": "https://mayacamasranch.com/"
   },
   {
    "file": "images/mayacamas-ranch/06.jpg",
    "w": 960,
    "h": 500,
    "caption": "Pasture looking toward Mount St. Helena at sunset, current post-fire landscape",
    "credit": "Mayacamas Ranch (official site)",
    "source": "https://mayacamasranch.com/"
   }
  ]
 },
 {
  "id": "ratna-ling",
  "tier": "REF",
  "name": "Ratna Ling",
  "area": "Cazadero, Sonoma coast",
  "drive": "~2 hr 30 min",
  "sleeps": "28",
  "meeting": "n/a",
  "buyout": "n/a",
  "why": "Gorgeous Tibetan Buddhist retreat center in the coastal hills, but too small for 60. Noted so it does not come up again.",
  "watch": "Ruled out on capacity",
  "phone": "(510) 809-4995",
  "email": "reservations@ratnaling.org",
  "website": "https://ratnaling.org/",
  "booking": "https://ratnaling.org/",
  "tierLabel": "Reference",
  "address": "35755 Hauser Bridge Road, Cazadero, CA 95421",
  "lat": 38.5984,
  "lng": -123.301,
  "geo_confidence": "high",
  "thumb": "images/ratna-ling/thumb.jpg",
  "images": [
   {
    "file": "images/ratna-ling/01.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Main lodge and terraced entry steps under a sunset sky",
    "credit": "Ratna Ling Retreat Center (official site; photo by Troy Ziel Photography)",
    "source": "https://ratnaling.org/"
   },
   {
    "file": "images/ratna-ling/02.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Timber-framed meditation hall with thangkas and shrine",
    "credit": "Ratna Ling Retreat Center (official site)",
    "source": "https://ratnaling.org/"
   },
   {
    "file": "images/ratna-ling/03.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Guest cottages on the hillside among redwoods and oaks",
    "credit": "Ratna Ling Retreat Center (official site)",
    "source": "https://ratnaling.org/"
   },
   {
    "file": "images/ratna-ling/04.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Covered timber walkway between the lodge buildings at dusk",
    "credit": "Ratna Ling Retreat Center (official site; photo by Troy Ziel Photography)",
    "source": "https://ratnaling.org/"
   },
   {
    "file": "images/ratna-ling/05.jpg",
    "w": 1600,
    "h": 1066,
    "caption": "Outdoor dining patio by the lodge",
    "credit": "Ratna Ling Retreat Center (official site)",
    "source": "https://ratnaling.org/"
   },
   {
    "file": "images/ratna-ling/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Entrance gate with prayer flags on Hauser Bridge Road",
    "credit": "Ratna Ling Retreat Center (official site; photo by Troy Ziel Photography)",
    "source": "https://ratnaling.org/"
   }
  ]
 },
 {
  "id": "green-gulch-farm",
  "tier": "REF",
  "name": "Green Gulch Farm",
  "area": "Muir Beach, Marin",
  "drive": "~45 min",
  "sleeps": "22",
  "meeting": "40 max",
  "buyout": "n/a",
  "why": "Zen Center farm in a coastal valley above Muir Beach. Gorgeous, but too small for 60, and not accepting new 2026 booking requests.",
  "watch": "Ruled out on capacity",
  "phone": "Email only",
  "email": "ggfconference@sfzc.org",
  "website": "https://www.sfzc.org/locations/green-gulch-farm",
  "booking": "https://www.sfzc.org/locations/green-gulch-farm/conference-center-green-gulch-facilities-rates-policies",
  "tierLabel": "Reference",
  "address": "1601 Shoreline Highway, Muir Beach, CA 94965",
  "lat": 37.8656,
  "lng": -122.5639,
  "geo_confidence": "high",
  "thumb": "images/green-gulch-farm/thumb.jpg",
  "images": [
   {
    "file": "images/green-gulch-farm/01.jpg",
    "w": 1600,
    "h": 1200,
    "caption": "Lindisfarne Guest House, the timber-frame guesthouse",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Green_Gulch_Farm_Zen_Center,_Lindisfarne_Guesthouse.jpg"
   },
   {
    "file": "images/green-gulch-farm/02.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Wheelwright Center, the conference/meeting building, among redwoods",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Wheelwright_Center_at_Green_Gulch_Farm_Zen_Center.jpg"
   },
   {
    "file": "images/green-gulch-farm/03.jpg",
    "w": 1150,
    "h": 768,
    "caption": "Aerial view down Green Gulch valley to Muir Beach",
    "credit": "San Francisco Zen Center (official site)",
    "source": "https://www.sfzc.org/locations/green-gulch-farm"
   },
   {
    "file": "images/green-gulch-farm/04.jpg",
    "w": 1600,
    "h": 1236,
    "caption": "Bell tower with the Japanese temple bell",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Green_Gulch_Farm_Zen_Center,_April_2017_-_03.jpg"
   },
   {
    "file": "images/green-gulch-farm/05.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Guesthouse sitting room with wood stove",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Green_Gulch_Farm_Zen_Center,_May_2019-5935.jpg"
   },
   {
    "file": "images/green-gulch-farm/06.jpg",
    "w": 1600,
    "h": 1067,
    "caption": "Guest room in the Lindisfarne Guest House",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Green_Gulch_Farm_Zen_Center,_May_2019-5934.jpg"
   }
  ]
 },
 {
  "id": "sea-ranch-lodge",
  "tier": "REF",
  "name": "Sea Ranch Lodge",
  "area": "The Sea Ranch, Sonoma coast",
  "drive": "~2 hr 30 min",
  "sleeps": "17",
  "meeting": "n/a",
  "buyout": "n/a",
  "why": "Iconic 1960s modernist lodge on the Sonoma coast bluffs. Gorgeous, but too small for 60. Noted so it does not come up again.",
  "watch": "Ruled out on capacity",
  "phone": "(707) 579-9777",
  "email": "",
  "website": "https://www.thesearanchlodge.com/",
  "booking": "https://www.thesearanchlodge.com/",
  "tierLabel": "Reference",
  "address": "60 Sea Walk Drive, The Sea Ranch, CA 95497",
  "lat": 38.68094,
  "lng": -123.4296,
  "geo_confidence": "high",
  "thumb": "images/sea-ranch-lodge/thumb.jpg",
  "images": [
   {
    "file": "images/sea-ranch-lodge/01.jpg",
    "w": 1600,
    "h": 1000,
    "caption": "Aerial view of the lodge on the bluffs above the cove",
    "credit": "The Sea Ranch Lodge (official site)",
    "source": "https://www.thesearanchlodge.com/lodging"
   },
   {
    "file": "images/sea-ranch-lodge/02.jpg",
    "w": 1600,
    "h": 1000,
    "caption": "Lodge rooms wing at sunset, looking down the coast",
    "credit": "The Sea Ranch Lodge (official site)",
    "source": "https://www.thesearanchlodge.com/lodging/lodge-rooms"
   },
   {
    "file": "images/sea-ranch-lodge/03.jpg",
    "w": 1600,
    "h": 1063,
    "caption": "Lodge exterior with the glass-walled dining room and meadow terrace (2024)",
    "credit": "Frank Schulenburg via Wikimedia Commons, CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sea_Ranch_Lodge,_Exterior_(2024)-L1004456.jpg"
   },
   {
    "file": "images/sea-ranch-lodge/04.jpg",
    "w": 1600,
    "h": 1000,
    "caption": "Lodge room with wood-burning stove and ocean-view window seat",
    "credit": "The Sea Ranch Lodge (official site)",
    "source": "https://www.thesearanchlodge.com/lodging/lodge-rooms"
   },
   {
    "file": "images/sea-ranch-lodge/05.jpg",
    "w": 1600,
    "h": 600,
    "caption": "North building courtyard at dusk",
    "credit": "The Sea Ranch Lodge (official site; photo by Adam Potts Photography)",
    "source": "https://www.thesearanchlodge.com/lodging"
   },
   {
    "file": "images/sea-ranch-lodge/06.jpg",
    "w": 1600,
    "h": 900,
    "caption": "Lodge entrance and Sea Ranch post office from the road",
    "credit": "The Sea Ranch Lodge (official site)",
    "source": "https://www.thesearanchlodge.com/"
   }
  ]
 }
];
